### ISSUE TITLE
question about strapi-user-permissions-jwt-cookie: replacement of ctx.send must be done in multiple places?

### ISSUE THREAD

**Issue by holygekko** [christopher-talke/talke-dev#1]
From you (excellent!) article about using httpOnly cookies with strapi I understand that you need to make adjustments in the ctx.send() method in Auth.js file. However that piece of code (that needs to be replaced) occurs 4 times in the copied Auth.js file. 

Am I right in guessing all 4 occurrences need to be replaced with the new code?

**Comment by christopher-talke** [comment]
Hi @holygekko,

I hope that I havn't stopped you from fixing anything, but to answer your question in my version I only changed it one place, which was lines 131 - 138.

The reason for this is because the ones at lines 166 - 173 & 209 - 215 were for third-party providers AND/OR password resets. You can change them if you'd like (i.e. if you're using a third-party OAuth provider **OR** if the password reset ctx.send(...) is breaking something for you), they just didn't apply in my use case so I didn't bother.

Hope that helps.

**Comment by christopher-talke** [comment]
Closing issue as there hasn't been a reply in over two (2) months.
